import type { Alert } from '@/types/inventory.types';

export const ALERTS: Alert[] = [
  {
    id: 'alr-001',
    severity: 'critical',
    type: 'low_stock',
    message: 'ELEC-SSD-001 below critical threshold — 4 units remaining (min: 10)',
    skuId: 'itm-001',
    sku: 'ELEC-SSD-001',
    skuName: '2TB NVMe SSD',
    currentQty: 4,
    minQty: 10,
    poId: null,
    timestamp: '2026-05-24T06:12:00Z',
    isAcknowledged: false,
    acknowledgedBy: null,
    acknowledgedAt: null,
  },
  {
    id: 'alr-002',
    severity: 'critical',
    type: 'low_stock',
    message: 'ELEC-RAM-001 stock critical — 6 units on hand, demand spike expected',
    skuId: 'itm-002',
    sku: 'ELEC-RAM-001',
    skuName: '32GB DDR5 RAM Kit',
    currentQty: 6,
    minQty: 15,
    poId: null,
    timestamp: '2026-05-24T04:55:00Z',
    isAcknowledged: false,
    acknowledgedBy: null,
    acknowledgedAt: null,
  },
  {
    id: 'alr-003',
    severity: 'critical',
    type: 'overdue_po',
    message: 'PO-2026-038 overdue by 3 days — DataLink International not responding',
    skuId: null,
    sku: null,
    skuName: null,
    currentQty: null,
    minQty: null,
    poId: 'po-003',
    timestamp: '2026-05-24T00:00:00Z',
    isAcknowledged: false,
    acknowledgedBy: null,
    acknowledgedAt: null,
  },
  {
    id: 'alr-004',
    severity: 'warning',
    type: 'low_stock',
    message: 'PRPH-KBD-001 approaching reorder point — 18 units (min: 20)',
    skuId: 'itm-003',
    sku: 'PRPH-KBD-001',
    skuName: 'Mechanical Keyboard TKL',
    currentQty: 18,
    minQty: 20,
    poId: null,
    timestamp: '2026-05-23T15:40:00Z',
    isAcknowledged: false,
    acknowledgedBy: null,
    acknowledgedAt: null,
  },
  {
    id: 'alr-005',
    severity: 'warning',
    type: 'discrepancy',
    message: 'Receiving discrepancy on PO-2026-041 — expected 50 units, scanned 47',
    skuId: 'itm-008',
    sku: 'CABL-USB-001',
    skuName: 'USB-C Cable 2m',
    currentQty: 47,
    minQty: 30,
    poId: 'po-005',
    timestamp: '2026-05-23T14:20:00Z',
    isAcknowledged: false,
    acknowledgedBy: null,
    acknowledgedAt: null,
  },
  {
    id: 'alr-006',
    severity: 'warning',
    type: 'low_stock',
    message: 'OFFC-INK-001 below reorder threshold — 12 sets on hand (min: 15)',
    skuId: 'itm-015',
    sku: 'OFFC-INK-001',
    skuName: 'Ink Cartridge Set',
    currentQty: 12,
    minQty: 15,
    poId: null,
    timestamp: '2026-05-23T12:35:00Z',
    isAcknowledged: false,
    acknowledgedBy: null,
    acknowledgedAt: null,
  },
  {
    id: 'alr-007',
    severity: 'info',
    type: 'receiving_pending',
    message: 'PO-2026-044 arriving today — 3 SKUs, TechBridge Supply Co.',
    skuId: null,
    sku: null,
    skuName: null,
    currentQty: null,
    minQty: null,
    poId: 'po-007',
    timestamp: '2026-05-24T07:00:00Z',
    isAcknowledged: false,
    acknowledgedBy: null,
    acknowledgedAt: null,
  },
  {
    id: 'alr-008',
    severity: 'info',
    type: 'receiving_pending',
    message: 'StorePro Logistics scheduled delivery 14:00 — dock B assigned',
    skuId: null,
    sku: null,
    skuName: null,
    currentQty: null,
    minQty: null,
    poId: 'po-006',
    timestamp: '2026-05-24T08:15:00Z',
    isAcknowledged: true,
    acknowledgedBy: 'op-jones',
    acknowledgedAt: '2026-05-24T09:30:00Z',
  },
];
